language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    
env:
    - INSTALL_PHP_INVOKER=0
    - INSTALL_PHP_INVOKER=1

before_script:
    - sh -c "if [ '$INSTALL_PHP_INVOKER' = '1' ]; then composer require --dev --prefer-source phpunit/php-invoker:~1.1; else composer install --dev --prefer-source; fi"

script: ./phpunit --configuration ./build/travis-ci.xml

notifications:
  email: 
    - manisha@shippable.com
